services:

  db:
    image: postgis/postgis:16-3.4
    container_name: stayhub_db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: stayhub_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  mongo:
    image: mongo:7.0.5
    container_name: stayhub_mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB:-stayhub}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build: ./backend
    container_name: stayhub_api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo

volumes:
  pgdata:
  mongodata: